#!/bin/bash

#. $TEST_ROOT_DIR/run-test-common

export KERAS_TEST_VERSION=2.0.6

export KERAS_BACKEND=cntk

# Device ID is passed through $TEST_DEVICE
# conftest.py transparently pulls in and extracts the Keras .zip

# TODO look at getting fewer exclusions

collection_ignores=(
  # Insufficient dependencies
  keras/backend/backend_test.py
)

test_ignores=(
    # Not in scope
    test_tfoptimizer
)

py.test \
  --verbose \
  $(printf -- "--ignore=keras-$KERAS_TEST_VERSION/tests/%s " ${collection_ignores[@]}) \
  -k "not just_a_dummy $(printf "and not %s " ${test_ignores[@]})" \
  keras-$KERAS_TEST_VERSION/tests && echo __COMPLETED__
