#!/bin/bash

#. $TEST_ROOT_DIR/run-test-common

export KERAS_TEST_VERSION=2.0.6

export KERAS_BACKEND=cntk

# Device ID is passed through $TEST_DEVICE
# conftest.py transparently pulls in and extracts the Keras .zip

# TODO look at getting fewer exclusions

collection_ignores=(
  # Insufficient dependencies
  keras/backend/backend_test.py
  # Not on Windows
  test_model_saving.py
  test_multiprocessing.py
  # Not in scope
  integration_tests
  test_documentation.py
)

test_ignores=(
    # Not in scope
    test_tfoptimizer
    # TODO investigation needed
    test_LambdaCallback
    test_conv3d_transpose
    test_convert_weights
    test_generator_enqueuer_fail_processes
    test_generator_enqueuer_processes
    test_generator_methods_interface
    test_has_arg_positional_only
    test_io_utils
    test_lambda
    test_merge
    test_warnings
)

py.test \
  --verbose \
  $(printf -- "--ignore=keras-$KERAS_TEST_VERSION/tests/%s " ${collection_ignores[@]}) \
  -k "not just_a_dummy $(printf "and not %s " ${test_ignores[@]})" \
  keras-$KERAS_TEST_VERSION/tests && echo __COMPLETED__
